# ============================================
# SENTINEL-AI — Kubernetes ConfigMap
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
  namespace: sentinel-prod
  labels:
    app: sentinel-api
data:
  MODEL_DIR: "/app/models"
  CHROMA_HOST: "chromadb-service"
  CHROMA_PORT: "8000"
  USE_API_LLM: "false"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "30"
  BERT_MODEL: "bert-base-uncased"
  BART_MODEL: "facebook/bart-large-cnn"
  NER_MODEL: "dslim/bert-base-NER"
  EMBEDDING_MODEL: "all-MiniLM-L6-v2"
  RERANKER_MODEL: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  LOG_LEVEL: "INFO"
  WORKERS: "2"
